name: Daily Leaderboard Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update_leaderboard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python script.py # Assurez-vous de mettre à jour le nom du script si nécessaire

      - name: Commit and push changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add leaderboard-crossplay.json
          git add leaderboard-psn.json
          git add leaderboard-steam.json
          git add leaderboard-xbox.json
          git commit -m "Update leaderboard (automated)"
          git push
