name: Daily Leaderboard Update

on:
  workflow_dispatch:

jobs:
  update_leaderboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python script.py # Assurez-vous de mettre à jour le nom du script si nécessaire

      - name: Commit and push changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add leaderboard.json
          git commit -m "Update leaderboard (automated)"
          git push
